---
fail_fast: true
exclude: |
    (?x)^(
      ^Test/.*$|
      ^Tools/.*$
    )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        files: ^.*\.(yaml|yml)$
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
        exclude: ^.*\.tftpl$
      - id: check-json
        files: ^.*\.json$
      - id: check-merge-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: detect-aws-credentials
      - id: end-of-file-fixer
      - id: forbid-submodules
      - id: no-commit-to-branch
      - id: pretty-format-json
        args: ['--autofix', --indent=2]
      - id: trailing-whitespace


  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.6
    hooks:
      - id: shellcheck

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        types: [file, yaml]
        args:
          - -c=./.yamllint

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.8.11
    hooks:
      - id: gitleaks

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint

  # - repo: https://github.com/python-jsonschema/check-jsonschema
  #   rev: 0.27.0
  #   hooks:
  #     - id: check-jsonschema
  #       files: ^config/.*\.json$
  #       types: [json]
  #       args: ["--verbose", "--schemafile", "./schema.json"]
