name: Test GitHub Pages

on:
  push:
    branches:
      - dev

jobs:
  preview:
    runs-on: ubuntu-latest
    name: Preview
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Preview
        run: yarn preview
        timeout-minutes: 1

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for response     
        uses: cygnetdigital/wait_for_response@v2.0.0
        with:
          url: 'http://localhost:4173/myself/'
          responseCode: '200,500'
          timeout: 9000
          interval: 500